version: "3.9"

services:
  vite-dev:
    build:
      context: .
      target: dev
    ports:
      - "8080:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  vite-prod:
    build:
      context: .
      target: prod
    ports:
      - "8080:5173"
    environment:
      - NODE_ENV=production
